# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e288fbe26307a21b83f7c0443e1d8fce"
name = "Python_Agent"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,write_inventory,read_inventory,write_customers,read_customers"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://example.com",
  "https://example.com/api/auth"
]

[build]
automatically_update_urls_on_dev = true
